name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Backend CI
        working-directory: ./backend
        run: |
          npm ci
          npm run lint
          npm run test

      - name: Frontend CI
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint
          npm run test
